# the connecting root frame will be named like this
connecting_frame_id: "common_origin"

# these are the tf subtrees to be connected through the respective root frames so that the equal frames are equal
connections:

  - root_frame_id: "uav1/fcu"
    equal_frame_id: "uav1/stable_origin"

  - root_frame_id: "uav2/fcu"
    equal_frame_id: "uav2/stable_origin"

  - root_frame_id: "uav3/fcu"
    equal_frame_id: "uav3/stable_origin"

  - root_frame_id: "uav6/fcu"
    equal_frame_id: "uav6/stable_origin"

  - root_frame_id: "uav7/fcu"
    equal_frame_id: "uav7/stable_origin"

  - root_frame_id: "uav8/fcu"
    equal_frame_id: "uav8/stable_origin"

  - root_frame_id: "uav9/fcu"
    equal_frame_id: "uav9/stable_origin"

  - root_frame_id: "uav10/fcu"
    equal_frame_id: "uav10/stable_origin"

  - root_frame_id: "uav11/fcu"
    equal_frame_id: "uav11/stable_origin"

  - root_frame_id: "uav12/fcu"
    equal_frame_id: "uav12/stable_origin"

  - root_frame_id: "uav13/fcu"
    equal_frame_id: "uav13/stable_origin"

  - root_frame_id: "uav14/fcu"
    equal_frame_id: "uav14/stable_origin"

  # you can add further connections here:
  # - root_frame_id: "another_root"
  #   equal_frame_id: "another_equal"

# if true, older messages than the last update of the respective frame connection will be ignored
ignore_older_messages: false

# if no update of a certain connection happens for this duration, it will be forced
max_update_period: 0.1 # seconds (set to zero to disable)
